### ISSUE TITLE
Radial gradient

### ISSUE THREAD

**Issue by akira-cn** [mesh-js/mesh.js#1]
Add mesh.setRadialGradient support.

```js
mesh.setRadialGradient({
  vector: [x0, y0, r0, x1, y1, r1],
  colors: [
    {offset: 0, color: [1, 0, 0, 1]},
    {offset: 1, color: [0, 1, 0, 1]},
  ],
  type: 'fill',
});
```

**Comment by lidongjies** [comment]
I'm ready to tackle this issue :), but I don't know much about the principle of the radial gradient, It may take me a few days to implement this feature.

**Comment by akira-cn** [comment]
I think we should use uniforms to implement radial gradient.

May be we can limit colorStops count to 8.

```glsl
uniform float u_colorStops[40]; // {offset, red, green, blue, alpha} * 8 -> sorted by offset
uniform float u_radialGradientVector[6]; // x0, y0, r0, x1, y1, r1
```

We calculate the distance between current positions and <x0, y0> and <x1, y1>.
And then we get the color from the distance according to u_colorStops.
