### ISSUE TITLE
Low performance compared to three.js

### ISSUE THREAD

**Issue by OverNothing** [mesh-js/mesh.js#13]
I tested the performance of mesh.js and three.js by drawing thousands of circles.
- [mesh.js demo](https://codepen.io/overnothing/pen/dyoYepB?editors=1010)
- [three.js demo](https://codepen.io/overnothing/pen/LYVRJjO?editors=0010)

The result shows three.js outperforms mesh.js.
When drawing 10,000 circles, fps of three.js remain around 38.
But mesh.js only has 17 fps.
Do you have any ideas about the reason of performance difference and how to improve mesh.js?

**Comment by akira-cn** [comment]
Hi, thanks to report this.

I optimized the performance now it's about 30fps.

It still has a little gap between mesh.js and three.js.

The two frameworks have different usage. Mesh.js uses different mechanism to render 2d objects and prepare fallbacks to canvas2d in some cases. Maybe the rendering mechanism of mesh.js consume a bit more than three.js.

Anyway, we will continue to optimize :)

**Comment by akira-cn** [comment]
BTW, you can use the experimental MeshCloud method (I will add to document soon).

MeshCloud gain much better performance.

[mesh.js demo use mesh-cloud](https://codepen.io/akira-cn/pen/yLYOzBd?editors=1010)
